import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav className="flex items-center justify-between flex-wrap bg-primary-foreground p-6">
          <div className="flex items-center flex-shrink-0 mr-6">
            3DS2 - Autenticación frictionless, sin 3DS Method
          </div>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
